version: "3.9"

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
